// ═══════════════════════════════════════════════════════
//  ODISHA COLLEGEHUB — DATABASE
//  All college, exam, news, scholarship, testimonial data
// ═══════════════════════════════════════════════════════

const COLLEGES = [
  {
    id: 1,
    name: 'IIT Bhubaneswar',
    short: 'IIT',
    loc: 'Argul, Bhubaneswar',
    type: 'Government',
    stream: 'Engineering',
    rating: 4.8,
    reviews: 2340,
    fees: '₹2.4L/yr',
    placement: '₹18 LPA',
    rank: 1,
    color: '#C0392B',
    badge: '🏆 IIT Premier',
    tags: ['B.Tech', 'M.Tech', 'PhD'],
    score: 97,
    website: 'https://www.iitbbs.ac.in',
    image: 'https://img.jagranjosh.com/images/2022/April/1242022/46345839_10155955082252742_998657841386487808_n.jpg',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e8/IIT_Bhubaneswar_Logo.svg/200px-IIT_Bhubaneswar_Logo.svg.png',
    desc: 'IIT Bhubaneswar is one of India\'s premier engineering institutes, established in 2008. Known for cutting-edge research, world-class faculty, and exceptional industry placements.',
    courses: [
      { name: 'B.Tech CSE', fee: '₹2.4L/yr', dur: '4 Years', seats: 80 },
      { name: 'B.Tech EEE', fee: '₹2.4L/yr', dur: '4 Years', seats: 60 },
      { name: 'M.Tech', fee: '₹28K/yr', dur: '2 Years', seats: 40 },
      { name: 'PhD', fee: '₹10K/yr', dur: '3-5 Years', seats: 30 }
    ],
    topRecruiter: 'Google, Microsoft, Amazon, Samsung',
    avgPkg: '₹18 LPA',
    highPkg: '₹1.2 CPA',
    placed: '95%',
    campus: '947 acres | Smart Classrooms | Olympic Pool | Stadium | Innovation Hub',
    estYear: 2008,
    accreditation: 'NAAC A++ | NBA',
    hostel: true,
    scholarship: true
  },
  {
    id: 2,
    name: 'NIT Rourkela',
    short: 'NIT',
    loc: 'Rourkela, Sundargarh',
    type: 'Government',
    stream: 'Engineering',
    rating: 4.7,
    reviews: 3120,
    fees: '₹1.4L/yr',
    placement: '₹14 LPA',
    rank: 2,
    color: '#1A5276',
    badge: '⭐ NIT Premier',
    tags: ['B.Tech', 'M.Tech', 'MBA'],
    score: 94,
    website: 'https://www.nitrkl.ac.in',
    image: 'https://www.thestatesman.com/wp-content/uploads/2019/06/nit.jpg',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d7/NIT_Rourkela_Logo.svg/200px-NIT_Rourkela_Logo.svg.png',
    desc: 'NIT Rourkela is one of the oldest and most prestigious NITs in India, established in 1961. Ranked consistently in India\'s top 20 engineering institutions.',
    courses: [
      { name: 'B.Tech CSE', fee: '₹1.4L/yr', dur: '4 Years', seats: 120 },
      { name: 'B.Tech Civil', fee: '₹1.4L/yr', dur: '4 Years', seats: 80 },
      { name: 'B.Tech ECE', fee: '₹1.4L/yr', dur: '4 Years', seats: 100 },
      { name: 'M.Tech', fee: '₹70K/yr', dur: '2 Years', seats: 60 }
    ],
    topRecruiter: 'TCS, Wipro, Infosys, TATA Steel',
    avgPkg: '₹14 LPA',
    highPkg: '₹45 LPA',
    placed: '88%',
    campus: '600 acres | Smart Classrooms | Olympic Pool | Stadium | Multiple Labs',
    estYear: 1961,
    accreditation: 'NAAC A+ | NBA',
    hostel: true,
    scholarship: true
  },
  {
    id: 3,
    name: 'AIIMS Bhubaneswar',
    short: 'AIIMS',
    loc: 'Sijua, Bhubaneswar',
    type: 'Government',
    stream: 'Medical',
    rating: 4.9,
    reviews: 890,
    fees: '₹1.6K/yr',
    placement: '₹12 LPA',
    rank: 3,
    color: '#1B4F72',
    badge: '🏥 Top Medical',
    tags: ['MBBS', 'MD/MS', 'Nursing'],
    score: 96,
    website: 'https://www.aiimsbhubaneswar.nic.in',
    image: 'https://ik.imagekit.io/syustaging/SYU_PREPROD/Campus-image_NSBeyQBEJ.webp?tr=w-3840',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/AIIMS_Bhubaneswar_Logo.svg/200px-AIIMS_Bhubaneswar_Logo.svg.png',
    desc: 'AIIMS Bhubaneswar is one of the new AIIMS established by the Government of India, offering world-class medical education and hospital facilities with 960-bed hospital.',
    courses: [
      { name: 'MBBS', fee: '₹1.6K/yr', dur: '5.5 Years', seats: 100 },
      { name: 'MD/MS', fee: '₹1.6K/yr', dur: '3 Years', seats: 50 },
      { name: 'B.Sc Nursing', fee: '₹10K/yr', dur: '4 Years', seats: 60 },
      { name: 'PhD', fee: '₹5K/yr', dur: '3 Years', seats: 20 }
    ],
    topRecruiter: 'Government Hospitals, Private Hospitals, Research',
    avgPkg: '₹12 LPA',
    highPkg: '₹28 LPA',
    placed: '100%',
    campus: '320 acres | 960-bed Hospital | Simulation Lab | Research Centre',
    estYear: 2012,
    accreditation: 'MCI Approved | NAAC A',
    hostel: true,
    scholarship: true
  },
  {
    id: 4,
    name: 'KIIT University',
    short: 'KIIT',
    loc: 'Patia, Bhubaneswar',
    type: 'Deemed',
    stream: 'Engineering',
    rating: 4.4,
    reviews: 4560,
    fees: '₹3.8L/yr',
    placement: '₹9 LPA',
    rank: 4,
    color: '#1A5C37',
    badge: '✨ Deemed Univ',
    tags: ['B.Tech', 'MBA', 'Law'],
    score: 82,
    website: 'https://www.kiit.ac.in',
    image: 'https://tse4.mm.bing.net/th/id/OIP.cTfJPNU1s2odGY38OY2K6gHaEK?rs=1&pid=ImgDetMain&o=7&rm=3',
    logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/KIIT_University_Logo.png/200px-KIIT_University_Logo.png',
    desc: 'KIIT is a leading deemed university offering diverse programs with vibrant campus life, strong industry connections, and excellent placements across engineering, management and law.',
    courses: [
      { name: 'B.Tech CSE', fee: '₹3.8L/yr', dur: '4 Years', seats: 600 },
      { name: 'MBA', fee: '₹3.5L/yr', dur: '2 Years', seats: 200 },
      { name: 'BBA', fee: '₹1.8L/yr', dur: '3 Years', seats: 300 },
      { name: 'LLB', fee: '₹1.6L/yr', dur: '3 Years', seats: 120 }
    ],
    topRecruiter: 'Cognizant, IBM, Deloitte, Accenture',
    avgPkg: '₹9 LPA',
    highPkg: '₹45 LPA',
    placed: '85%',
    campus: '25 acres | Multiple Hostels | 24x7 Medical | Food Courts',
    estYear: 1992,
    accreditation: 'NAAC A | NBA',
    hostel: true,
    scholarship: true
  },
  {
    id: 5,
    name: 'SOA University',
    short: 'SoA',
    loc: 'Khandagiri, Bhubaneswar',
    type: 'Deemed',
    stream: 'Medical',
    rating: 4.3,
    reviews: 3200,
    fees: '₹2.9L/yr',
    placement: '₹8 LPA',
    rank: 5,
    color: '#6C3483',
    badge: '🎓 Deemed',
    tags: ['Medical', 'Engineering'],
    score: 78,
    website: 'https://www.soauniversity.ac.in',
    image: 'https://images.squarespace-cdn.com/content/v1/57713a8e2994cae381dd86fe/52a41d44-8933-41c6-96fe-ad9996c3ca16/DJI_0104_121-1.jpg',
    logo: '',
    desc: 'SOA University offers comprehensive professional courses with 1600-bed hospital, research centers and modern infrastructure for medical and engineering programs.',
    courses: [
      { name: 'MBBS', fee: '₹14L/yr', dur: '5.5 Years', seats: 150 },
      { name: 'B.Tech', fee: '₹2.9L/yr', dur: '4 Years', seats: 400 },
      { name: 'MBA', fee: '₹2L/yr', dur: '2 Years', seats: 120 },
      { name: 'Pharmacy', fee: '₹1.8L/yr', dur: '4 Years', seats: 100 }
    ],
    topRecruiter: 'Apollo Hospitals, Fortis, Tata',
    avgPkg: '₹8 LPA',
    highPkg: '₹22 LPA',
    placed: '80%',
    campus: '400 acres | 1600-bed Hospital | Research Center | Sports Complex',
    estYear: 1996,
    accreditation: 'NAAC A | MCI',
    hostel: true,
    scholarship: false
  },
  {
    id: 6,
    name: 'Utkal University',
    short: 'UU',
    loc: 'Vani Vihar, Bhubaneswar',
    type: 'Government',
    stream: 'Arts',
    rating: 4.1,
    reviews: 5600,
    fees: '₹28K/yr',
    placement: '₹4 LPA',
    rank: 6,
    color: '#784212',
    badge: '🏛️ State Univ',
    tags: ['Arts', 'Science', 'Commerce'],
    score: 72,
    website: 'https://www.utkaluniversity.ac.in',
    image: 'https://utkalalumni.in/assets/img/about-page/about-img-1.jpg',
    logo: '',
    desc: 'Utkal University, established in 1943, is the oldest and largest university in Odisha, offering diverse UG and PG programs with a rich heritage campus.',
    courses: [
      { name: 'BA', fee: '₹28K/yr', dur: '3 Years', seats: 800 },
      { name: 'B.Sc', fee: '₹28K/yr', dur: '3 Years', seats: 500 },
      { name: 'M.A', fee: '₹35K/yr', dur: '2 Years', seats: 300 },
      { name: 'MBA', fee: '₹80K/yr', dur: '2 Years', seats: 80 }
    ],
    topRecruiter: 'State Govt, NGOs, Journalism, Banking',
    avgPkg: '₹4 LPA',
    highPkg: '₹10 LPA',
    placed: '65%',
    campus: '400 acres | Heritage Campus | Central Library | Sports Ground',
    estYear: 1943,
    accreditation: 'NAAC A',
    hostel: true,
    scholarship: true
  },
  {
    id: 7,
    name: 'VSSUT Burla',
    short: 'VSS',
    loc: 'Burla, Sambalpur',
    type: 'Government',
    stream: 'Engineering',
    rating: 4.3,
    reviews: 1890,
    fees: '₹85K/yr',
    placement: '₹7 LPA',
    rank: 7,
    color: '#145A32',
    badge: '⚡ Top Eng',
    tags: ['B.Tech', 'M.Tech'],
    score: 76,
    website: 'https://www.vssut.ac.in',
    image: 'https://tse4.mm.bing.net/th/id/OIP.yF35ppN58wf9uvwj8y-MEgHaE6?rs=1&pid=ImgDetMain&o=7&rm=3',
    logo: '',
    desc: 'VSSUT Burla is a leading government technical university in western Odisha, producing quality engineers with strong industry connections in core sectors.',
    courses: [
      { name: 'B.Tech EEE', fee: '₹85K/yr', dur: '4 Years', seats: 120 },
      { name: 'B.Tech Civil', fee: '₹85K/yr', dur: '4 Years', seats: 100 },
      { name: 'B.Tech Mech', fee: '₹85K/yr', dur: '4 Years', seats: 100 },
      { name: 'M.Tech', fee: '₹30K/yr', dur: '2 Years', seats: 40 }
    ],
    topRecruiter: 'NALCO, SAIL, Vedanta, L&T',
    avgPkg: '₹7 LPA',
    highPkg: '₹22 LPA',
    placed: '75%',
    campus: '220 acres | Central Library | Sports Facilities | Research Labs',
    estYear: 1956,
    accreditation: 'NAAC B++ | NBA',
    hostel: true,
    scholarship: true
  },
  {
    id: 8,
    name: 'OUAT Bhubaneswar',
    short: 'OUA',
    loc: 'Bhubaneswar',
    type: 'Government',
    stream: 'Science',
    rating: 4.2,
    reviews: 740,
    fees: '₹65K/yr',
    placement: '₹5 LPA',
    rank: 8,
    color: '#1A5276',
    badge: '🌾 Agriculture',
    tags: ['B.Sc Ag', 'M.Sc'],
    score: 73,
    website: 'https://www.ouat.ac.in',
    image: 'https://th.bing.com/th/id/R.f13e6cdb4c6a08fd609d8153f8dcb7b8?rik=DwfV8DobT7Oqeg&riu=http%3a%2f%2fphotos.wikimapia.org%2fp%2f00%2f00%2f39%2f08%2f83_big.jpg&ehk=CB2N%2fhbA2fOEWgK%2fZKOX%2bCOxlTlSMppgEFCkSoAYy0E%3d&risl=&pid=ImgRaw&r=0',
    logo: '',
    desc: 'OUAT is the premier agricultural university in Odisha with an 800-acre campus, experimental farms, and research stations producing agri professionals.',
    courses: [
      { name: 'B.Sc Agriculture', fee: '₹65K/yr', dur: '4 Years', seats: 200 },
      { name: 'M.Sc Agriculture', fee: '₹40K/yr', dur: '2 Years', seats: 80 },
      { name: 'Ph.D', fee: '₹25K/yr', dur: '3 Years', seats: 30 }
    ],
    topRecruiter: 'NABARD, Agri startups, Govt. Depts.',
    avgPkg: '₹5 LPA',
    highPkg: '₹14 LPA',
    placed: '70%',
    campus: '800 acres | Experimental Farm | Research Station | Dairy Plant',
    estYear: 1962,
    accreditation: 'NAAC B+',
    hostel: true,
    scholarship: true
  },
  {
    id: 9,
    name: 'KIMS Bhubaneswar',
    short: 'KIMS',
    loc: 'Patia, Bhubaneswar',
    type: 'Private',
    stream: 'Medical',
    rating: 4.5,
    reviews: 1100,
    fees: '₹14L/yr',
    placement: '₹10 LPA',
    rank: 9,
    color: '#922B21',
    badge: '🏥 Medical',
    tags: ['MBBS', 'MD', 'BDS'],
    score: 80,
    website: 'https://www.kims.ac.in',
    image: 'https://th.bing.com/th/id/OIP.P1fUJRhWNG8tePJU94h_KAHaFf?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
    logo: '',
    desc: 'KIMS is among the top private medical colleges in Odisha, offering world-class medical education with a 1050-bed hospital and state-of-the-art simulation lab.',
    courses: [
      { name: 'MBBS', fee: '₹14L/yr', dur: '5.5 Years', seats: 150 },
      { name: 'MD/MS', fee: '₹8L/yr', dur: '3 Years', seats: 60 },
      { name: 'BDS', fee: '₹6L/yr', dur: '5 Years', seats: 60 }
    ],
    topRecruiter: 'Apollo, Fortis, Max Healthcare, AIIMS',
    avgPkg: '₹10 LPA',
    highPkg: '₹24 LPA',
    placed: '95%',
    campus: '100 acres | 1050-bed Hospital | Simulation Centre | Library',
    estYear: 1997,
    accreditation: 'MCI | NAAC A',
    hostel: true,
    scholarship: false
  },
  {
    id: 10,
    name: 'XIM University',
    short: 'XIM',
    loc: 'Bhubaneswar',
    type: 'Private',
    stream: 'MBA',
    rating: 4.6,
    reviews: 680,
    fees: '₹17L/yr',
    placement: '₹22 LPA',
    rank: 10,
    color: '#1A3A5C',
    badge: '💼 Top MBA',
    tags: ['MBA', 'PGDM'],
    score: 88,
    website: 'https://www.xim.edu.in',
    image: 'https://odishastudents.org/storage/2021/11/xavier-university-odishastudents-org.jpg',
    logo: '',
    desc: 'XIM University (formerly XIMB) is one of India\'s top 10 business schools, renowned for exceptional management education, Bloomberg terminal access, and incredible alumni network.',
    courses: [
      { name: 'MBA (BM)', fee: '₹17L/yr', dur: '2 Years', seats: 120 },
      { name: 'MBA (HRM)', fee: '₹15L/yr', dur: '2 Years', seats: 60 },
      { name: 'MBA (RM)', fee: '₹14L/yr', dur: '2 Years', seats: 60 }
    ],
    topRecruiter: 'Goldman Sachs, McKinsey, HDFC, Deloitte',
    avgPkg: '₹22 LPA',
    highPkg: '₹68 LPA',
    placed: '100%',
    campus: '25 acres | Smart Campus | Bloomberg Terminal | Amphitheatre',
    estYear: 1987,
    accreditation: 'AACSB | NAAC A+',
    hostel: true,
    scholarship: true
  },
  {
    id: 11,
    name: 'Orissa Engineering College',
    short: 'OEC',
    loc: 'Bhubaneswar',
    type: 'Private',
    stream: 'Engineering',
    rating: 3.9,
    reviews: 1200,
    fees: '₹1.2L/yr',
    placement: '₹5 LPA',
    rank: 11,
    color: '#2E4053',
    badge: '',
    tags: ['B.Tech', 'MCA'],
    score: 65,
    website: 'https://www.oec.edu.in',
    image: 'https://www.gkseries.com/blog/wp-content/uploads/2020/04/Orissa-Engineering-College-Jatni.jpg',
    logo: '',
    desc: 'OEC is a well-established private engineering college with diverse B.Tech programs, experienced faculty, and strong industry partnerships with Odisha IT sector.',
    courses: [
      { name: 'B.Tech CSE', fee: '₹1.2L/yr', dur: '4 Years', seats: 180 },
      { name: 'B.Tech ECE', fee: '₹1.2L/yr', dur: '4 Years', seats: 120 },
      { name: 'MCA', fee: '₹80K/yr', dur: '3 Years', seats: 60 }
    ],
    topRecruiter: 'TCS, Infosys, Wipro, HCL',
    avgPkg: '₹5 LPA',
    highPkg: '₹12 LPA',
    placed: '68%',
    campus: '30 acres | Hostel | Library | Computer Labs',
    estYear: 1986,
    accreditation: 'NAAC B | AICTE',
    hostel: true,
    scholarship: false
  },
  {
    id: 12,
    name: 'Sambalpur University',
    short: 'SU',
    loc: 'Sambalpur',
    type: 'Government',
    stream: 'Arts',
    rating: 3.8,
    reviews: 2400,
    fees: '₹24K/yr',
    placement: '₹3.5 LPA',
    rank: 12,
    color: '#6E2F0A',
    badge: '🏛️ Univ',
    tags: ['Arts', 'Science', 'Law'],
    score: 62,
    website: 'https://www.samu.ac.in',
    image: 'https://th.bing.com/th/id/OIP.HjMJZSITzm4OP49sWc9zhQHaE8?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
    logo: '',
    desc: 'Sambalpur University serves western Odisha with diverse programs. Established in 1967 with a sprawling campus, it is known for arts, science and law education.',
    courses: [
      { name: 'BA', fee: '₹24K/yr', dur: '3 Years', seats: 600 },
      { name: 'B.Sc', fee: '₹24K/yr', dur: '3 Years', seats: 400 },
      { name: 'LLB', fee: '₹35K/yr', dur: '3 Years', seats: 100 }
    ],
    topRecruiter: 'State Govt, Law Firms, Banks, NGOs',
    avgPkg: '₹3.5 LPA',
    highPkg: '₹9 LPA',
    placed: '55%',
    campus: '350 acres | Stadium | Hostels | Library | NCC',
    estYear: 1967,
    accreditation: 'NAAC B++',
    hostel: true,
    scholarship: true
  },
  {
  id: 13,
  name: 'ITER SOA',
  short: 'ITER',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Engineering',
  rating: 4.2,
  reviews: 2100,
  fees: '₹2.5L/yr',
  placement: '₹7 LPA',
  rank: 13,
  color: '#7D3C98',
  badge: '⚙️ Engineering',
  tags: ['B.Tech', 'M.Tech'],
  score: 74,
  website: 'https://www.soa.ac.in/iter',
  image: 'https://tse4.mm.bing.net/th/id/OIP.bK-_PPLeMcM8FWPa1XB2zAAAAA?w=358&h=239&rs=1&pid=ImgDetMain&o=7&rm=3',
  logo: '',
  desc: 'ITER is the engineering institute of SOA University with strong placements and modern labs.',
  courses: [
    { name: 'B.Tech CSE', fee: '₹2.5L/yr', dur: '4 Years', seats: 300 },
    { name: 'B.Tech ECE', fee: '₹2.5L/yr', dur: '4 Years', seats: 200 }
  ],
  topRecruiter: 'TCS, Infosys, Capgemini',
  avgPkg: '₹7 LPA',
  highPkg: '₹20 LPA',
  placed: '82%',
  campus: 'Tech Labs | Hostels | Library',
  estYear: 1996,
  accreditation: 'NAAC A',
  hostel: true,
  scholarship: true
},

{
  id: 14,
  name: 'GITA Autonomous College',
  short: 'GITA',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Engineering',
  rating: 4.1,
  reviews: 1800,
  fees: '₹1.3L/yr',
  placement: '₹5 LPA',
  rank: 14,
  color: '#1F618D',
  badge: '🎓 Autonomous',
  tags: ['B.Tech', 'MBA'],
  score: 70,
  website: 'https://www.gita.edu.in',
  image: 'https://i.ytimg.com/vi/lsOMRW5GPec/maxresdefault.jpg',
  logo: '',
  desc: 'GITA is a top autonomous engineering college known for discipline and placements.',
  courses: [
    { name: 'B.Tech', fee: '₹1.3L/yr', dur: '4 Years', seats: 400 }
  ],
  topRecruiter: 'Wipro, TCS, Cognizant',
  avgPkg: '₹5 LPA',
  highPkg: '₹12 LPA',
  placed: '75%',
  campus: 'Smart Campus | Labs | Hostel',
  estYear: 2004,
  accreditation: 'NAAC A',
  hostel: true,
  scholarship: false
},

{
  id: 15,
  name: 'CV Raman Global University',
  short: 'CGU',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Engineering',
  rating: 4.3,
  reviews: 2500,
  fees: '₹2L/yr',
  placement: '₹6 LPA',
  rank: 15,
  color: '#117864',
  badge: '🌟 University',
  tags: ['B.Tech', 'MBA'],
  score: 76,
  website: 'https://www.cgu-odisha.ac.in',
  image: 'https://cache.careers360.mobi/media/colleges/social-media/media-gallery/4738/2018/5/7/Campus-View-1.jpg',
  logo: '',
  desc: 'CGU is a fast-growing private university with modern infrastructure and good placements.',
  courses: [
    { name: 'B.Tech', fee: '₹2L/yr', dur: '4 Years', seats: 500 }
  ],
  topRecruiter: 'Infosys, Capgemini, Tech Mahindra',
  avgPkg: '₹6 LPA',
  highPkg: '₹18 LPA',
  placed: '80%',
  campus: 'Green Campus | Labs | Sports',
  estYear: 2020,
  accreditation: 'UGC',
  hostel: true,
  scholarship: true
},

{
  id: 16,
  name: 'Silicon Institute of Technology',
  short: 'SIT',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Engineering',
  rating: 4.2,
  reviews: 1600,
  fees: '₹1.5L/yr',
  placement: '₹6.5 LPA',
  rank: 16,
  color: '#2C3E50',
  badge: '💻 IT Focus',
  tags: ['B.Tech'],
  score: 75,
  website: 'https://silicon.ac.in',
  image: 'https://erp.silicon.ac.in/estcampus/images/slider/fcc8c71c522bdb7ced4e4096611e31d7.jpg',
  logo: '',
  desc: 'Silicon is known for coding culture and strong IT placements.',
  courses: [
    { name: 'B.Tech CSE', fee: '₹1.5L/yr', dur: '4 Years', seats: 240 }
  ],
  topRecruiter: 'Amazon, Infosys, TCS Digital',
  avgPkg: '₹6.5 LPA',
  highPkg: '₹30 LPA',
  placed: '85%',
  campus: 'Modern Labs | Coding Culture',
  estYear: 2001,
  accreditation: 'NAAC A',
  hostel: true,
  scholarship: true
},

{
  id: 17,
  name: 'IIIT Bhubaneswar',
  short: 'IIIT',
  loc: 'Bhubaneswar',
  type: 'Government',
  stream: 'Engineering',
  rating: 4.5,
  reviews: 900,
  fees: '₹2L/yr',
  placement: '₹12 LPA',
  rank: 17,
  color: '#154360',
  badge: '🏆 IIIT',
  tags: ['B.Tech', 'M.Tech'],
  score: 85,
  website: 'https://www.iiit-bh.ac.in',
  image: 'https://th.bing.com/th/id/OIP.VWNq5npoo5U6nKEkClbl8AHaEK?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
  logo: '',
  desc: 'IIIT Bhubaneswar focuses on IT and research with strong placement records.',
  courses: [
    { name: 'B.Tech IT', fee: '₹2L/yr', dur: '4 Years', seats: 180 }
  ],
  topRecruiter: 'Amazon, Microsoft, Adobe',
  avgPkg: '₹12 LPA',
  highPkg: '₹45 LPA',
  placed: '90%',
  campus: 'Tech Campus | Research Labs',
  estYear: 2006,
  accreditation: 'NAAC',
  hostel: true,
  scholarship: true
},
{
  id: 18,
  name: 'Ravenshaw University',
  short: 'RU',
  loc: 'Cuttack',
  type: 'Government',
  stream: 'Arts',
  rating: 4.4,
  reviews: 4200,
  fees: '₹35K/yr',
  placement: '₹5 LPA',
  rank: 18,
  color: '#7B241C',
  badge: '🏛️ Heritage',
  tags: ['Arts', 'Science', 'Commerce'],
  score: 78,
  website: 'https://ravenshawuniversity.ac.in',
  image: 'https://ravenshawuniversity.ac.in/fornt-scroll/1c.jpg',
  logo: '',
  desc: 'Ravenshaw University is one of the oldest institutions in India with strong academic reputation.',
  courses: [
    { name: 'BA', fee: '₹35K/yr', dur: '3 Years', seats: 600 },
    { name: 'B.Sc', fee: '₹40K/yr', dur: '3 Years', seats: 400 }
  ],
  topRecruiter: 'Govt, NGOs, Banks',
  avgPkg: '₹5 LPA',
  highPkg: '₹12 LPA',
  placed: '70%',
  campus: 'Historic Campus | Library | Sports',
  estYear: 1868,
  accreditation: 'NAAC A',
  hostel: true,
  scholarship: true
},

{
  id: 19,
  name: 'FM University',
  short: 'FMU',
  loc: 'Balasore',
  type: 'Government',
  stream: 'Arts',
  rating: 3.9,
  reviews: 1500,
  fees: '₹30K/yr',
  placement: '₹4 LPA',
  rank: 19,
  color: '#5B2C6F',
  badge: '🎓 State Univ',
  tags: ['Arts', 'Science'],
  score: 65,
  website: 'https://fmuniversity.nic.in',
  image: 'https://i.ytimg.com/vi/SNxLGfoi1rQ/hqdefault.jpg',
  logo: '',
  desc: 'Fakir Mohan University serves northern Odisha with UG and PG programs.',
  courses: [
    { name: 'BA', fee: '₹30K/yr', dur: '3 Years', seats: 500 },
    { name: 'M.Sc', fee: '₹45K/yr', dur: '2 Years', seats: 150 }
  ],
  topRecruiter: 'Govt Jobs, Teaching',
  avgPkg: '₹4 LPA',
  highPkg: '₹9 LPA',
  placed: '60%',
  campus: 'Green Campus | Labs',
  estYear: 1999,
  accreditation: 'NAAC B+',
  hostel: true,
  scholarship: true
},

{
  id: 20,
  name: 'Centurion University',
  short: 'CUTM',
  loc: 'Paralakhemundi',
  type: 'Private',
  stream: 'Engineering',
  rating: 4.1,
  reviews: 1700,
  fees: '₹1.8L/yr',
  placement: '₹6 LPA',
  rank: 20,
  color: '#1E8449',
  badge: '⚙️ Skill Based',
  tags: ['B.Tech', 'Diploma'],
  score: 72,
  website: 'https://cutm.ac.in',
  image: 'https://th.bing.com/th/id/OIP.FSGehzBCCO9ipfxFw_9bsgHaDt?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
  logo: '',
  desc: 'Centurion University focuses on skill-based education and industry training.',
  courses: [
    { name: 'B.Tech', fee: '₹1.8L/yr', dur: '4 Years', seats: 300 }
  ],
  topRecruiter: 'L&T, Tata Projects',
  avgPkg: '₹6 LPA',
  highPkg: '₹15 LPA',
  placed: '78%',
  campus: 'Skill Labs | Workshops',
  estYear: 2005,
  accreditation: 'NAAC A',
  hostel: true,
  scholarship: true
},

{
  id: 21,
  name: 'Hi-Tech Medical College',
  short: 'HTMC',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Medical',
  rating: 4.0,
  reviews: 900,
  fees: '₹12L/yr',
  placement: '₹9 LPA',
  rank: 21,
  color: '#922B21',
  badge: '🏥 Medical',
  tags: ['MBBS'],
  score: 70,
  website: 'https://hitechmedicalcollege.org',
  image: 'https://blog.rmgoe.org/wp-content/uploads/2022/09/Hi-Tech-Medical-College-Bhubaneswar-1.webp',
  logo: '',
  desc: 'Hi-Tech Medical College provides quality medical education with hospital training.',
  courses: [
    { name: 'MBBS', fee: '₹12L/yr', dur: '5.5 Years', seats: 150 }
  ],
  topRecruiter: 'Hospitals, Clinics',
  avgPkg: '₹9 LPA',
  highPkg: '₹20 LPA',
  placed: '90%',
  campus: 'Hospital | Labs | Hostels',
  estYear: 2005,
  accreditation: 'MCI',
  hostel: true,
  scholarship: false
},

{
  id: 22,
  name: 'Gandhi Institute for Technology',
  short: 'GIFT',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Engineering',
  rating: 3.8,
  reviews: 1300,
  fees: '₹1.2L/yr',
  placement: '₹4.5 LPA',
  rank: 22,
  color: '#2E4053',
  badge: '🎓 Engineering',
  tags: ['B.Tech'],
  score: 64,
  website: 'https://gift.edu.in',
  image: 'https://tse3.mm.bing.net/th/id/OIP.p-DVdMEYkYwNj1LrlRwBqwHaFj?rs=1&pid=ImgDetMain&o=7&rm=3',
  logo: '',
  desc: 'GIFT is a well-known engineering college with decent placements.',
  courses: [
    { name: 'B.Tech', fee: '₹1.2L/yr', dur: '4 Years', seats: 360 }
  ],
  topRecruiter: 'Infosys, TCS',
  avgPkg: '₹4.5 LPA',
  highPkg: '₹10 LPA',
  placed: '68%',
  campus: 'Labs | Hostel | Library',
  estYear: 2007,
  accreditation: 'AICTE',
  hostel: true,
  scholarship: false
},
{
  id: 23,
  name: 'Government College of Engineering Kalahandi',
  short: 'GCEK',
  loc: 'Bhawanipatna',
  type: 'Government',
  stream: 'Engineering',
  rating: 4.0,
  reviews: 900,
  fees: '₹80K/yr',
  placement: '₹5 LPA',
  rank: 23,
  color: '#196F3D',
  badge: '🏛️ Govt Engg',
  tags: ['B.Tech'],
  score: 71,
  website: 'https://gcekbpatna.ac.in',
  image: 'https://image-static.collegedunia.com/public/reviewPhotos/1043774/1000027678.jpg',
  logo: '',
  desc: 'GCEK is a government engineering college providing affordable technical education in western Odisha.',
  courses: [
    { name: 'B.Tech Civil', fee: '₹80K/yr', dur: '4 Years', seats: 120 },
    { name: 'B.Tech Mech', fee: '₹80K/yr', dur: '4 Years', seats: 120 }
  ],
  topRecruiter: 'TCS, Vedanta',
  avgPkg: '₹5 LPA',
  highPkg: '₹12 LPA',
  placed: '70%',
  campus: 'Labs | Hostels | Library',
  estYear: 2009,
  accreditation: 'AICTE',
  hostel: true,
  scholarship: true
},

{
  id: 24,
  name: 'Parala Maharaja Engineering College',
  short: 'PMEC',
  loc: 'Berhampur',
  type: 'Government',
  stream: 'Engineering',
  rating: 4.1,
  reviews: 1100,
  fees: '₹90K/yr',
  placement: '₹5.5 LPA',
  rank: 24,
  color: '#1A5276',
  badge: '⚙️ Govt Engg',
  tags: ['B.Tech'],
  score: 73,
  website: 'https://pmec.ac.in',
  image: 'https://pmec.ac.in/wp-content/uploads/2023/07/IMG_3824-scaled.jpg',
  logo: '',
  desc: 'PMEC is a reputed government engineering college with steady placement growth.',
  courses: [
    { name: 'B.Tech ECE', fee: '₹90K/yr', dur: '4 Years', seats: 120 }
  ],
  topRecruiter: 'Infosys, TCS',
  avgPkg: '₹5.5 LPA',
  highPkg: '₹14 LPA',
  placed: '72%',
  campus: 'Green Campus | Labs',
  estYear: 2009,
  accreditation: 'AICTE',
  hostel: true,
  scholarship: true
},

{
  id: 25,
  name: 'Indira Gandhi Institute of Technology',
  short: 'IGIT',
  loc: 'Sarang, Dhenkanal',
  type: 'Government',
  stream: 'Engineering',
  rating: 4.3,
  reviews: 2000,
  fees: '₹85K/yr',
  placement: '₹6.5 LPA',
  rank: 25,
  color: '#512E5F',
  badge: '🏛️ Top Govt',
  tags: ['B.Tech', 'M.Tech'],
  score: 77,
  website: 'https://igitsarang.ac.in',
  image: 'https://media.getmyuni.com/reviews/23062__3404/1476169673DSC02584.jpg',
  logo: '',
  desc: 'IGIT Sarang is one of Odisha’s top government engineering institutes with strong core placements.',
  courses: [
    { name: 'B.Tech Mechanical', fee: '₹85K/yr', dur: '4 Years', seats: 180 }
  ],
  topRecruiter: 'NALCO, Tata Steel',
  avgPkg: '₹6.5 LPA',
  highPkg: '₹20 LPA',
  placed: '80%',
  campus: '300 acres | Workshops | Labs',
  estYear: 1982,
  accreditation: 'NAAC B+',
  hostel: true,
  scholarship: true
},

{
  id: 26,
  name: 'SCB Medical College',
  short: 'SCB',
  loc: 'Cuttack',
  type: 'Government',
  stream: 'Medical',
  rating: 4.6,
  reviews: 1500,
  fees: '₹30K/yr',
  placement: '₹10 LPA',
  rank: 26,
  color: '#943126',
  badge: '🏥 Govt Medical',
  tags: ['MBBS', 'MD'],
  score: 90,
  website: 'https://scbmch.nic.in',
  image: 'https://i.ytimg.com/vi/8FA8LJMOUDo/maxresdefault.jpg?sqp=-oaymwEmCIAKENAF8quKqQMa8AEB-AH-CYAC0AWKAgwIABABGCEgZShUMA8=&rs=AOn4CLCcp8F2Yi3SMkJofihj9Isu9bFCug',
  logo: '',
  desc: 'SCB Medical College is one of the oldest and most prestigious medical institutions in Odisha.',
  courses: [
    { name: 'MBBS', fee: '₹30K/yr', dur: '5.5 Years', seats: 250 }
  ],
  topRecruiter: 'Govt Hospitals',
  avgPkg: '₹10 LPA',
  highPkg: '₹25 LPA',
  placed: '100%',
  campus: 'Large Hospital | Labs | Hostels',
  estYear: 1944,
  accreditation: 'MCI',
  hostel: true,
  scholarship: true
},

{
  id: 27,
  name: 'Dhenkanal Autonomous College',
  short: 'DAC',
  loc: 'Dhenkanal',
  type: 'Government',
  stream: 'Arts',
  rating: 3.9,
  reviews: 1300,
  fees: '₹25K/yr',
  placement: '₹3.5 LPA',
  rank: 27,
  color: '#7E5109',
  badge: '🎓 Autonomous',
  tags: ['Arts', 'Science'],
  score: 63,
  website: 'https://dhenkanalcollege.ac.in',
  image: 'https://www.collegesmba.in/wp-content/uploads/2016/01/Dhenkanal-College-Campus.png',
  logo: '',
  desc: 'Dhenkanal Autonomous College is a reputed institution offering UG and PG courses.',
  courses: [
    { name: 'BA', fee: '₹25K/yr', dur: '3 Years', seats: 600 }
  ],
  topRecruiter: 'Govt Jobs, Teaching',
  avgPkg: '₹3.5 LPA',
  highPkg: '₹8 LPA',
  placed: '55%',
  campus: 'Library | Playground',
  estYear: 1959,
  accreditation: 'NAAC B+',
  hostel: true,
  scholarship: true
},
{
  id: 28,
  name: 'Kalinga Institute of Medical Sciences',
  short: 'KIMS',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Medical',
  rating: 4.4,
  reviews: 1400,
  fees: '₹14L/yr',
  placement: '₹10 LPA',
  rank: 28,
  color: '#7B241C',
  badge: '🏥 Medical',
  tags: ['MBBS', 'MD'],
  score: 82,
  website: 'https://kims.kiit.ac.in',
  image: 'https://hospital.kims.ac.in/wp-content/uploads/2024/09/KIMS-Super-Speciality-Hospital-3.jpg',
  logo: '',
  desc: 'KIMS is a top private medical college with advanced hospital facilities and research labs.',
  courses: [
    { name: 'MBBS', fee: '₹14L/yr', dur: '5.5 Years', seats: 150 }
  ],
  topRecruiter: 'Hospitals, Research Centers',
  avgPkg: '₹10 LPA',
  highPkg: '₹22 LPA',
  placed: '95%',
  campus: 'Hospital | Labs | Library',
  estYear: 2007,
  accreditation: 'MCI',
  hostel: true,
  scholarship: false
},

{
  id: 29,
  name: 'Veer Surendra Sai Institute of Medical Sciences',
  short: 'VIMSAR',
  loc: 'Burla',
  type: 'Government',
  stream: 'Medical',
  rating: 4.5,
  reviews: 1200,
  fees: '₹40K/yr',
  placement: '₹9 LPA',
  rank: 29,
  color: '#922B21',
  badge: '🏛️ Govt Medical',
  tags: ['MBBS', 'MD'],
  score: 88,
  website: 'https://vimsar.ac.in',
  image: 'https://rmgoe.org/universities/India/images/1751700306_6868d3520ab80.png',
  logo: '',
  desc: 'VIMSAR Burla is a reputed government medical college with strong clinical exposure.',
  courses: [
    { name: 'MBBS', fee: '₹40K/yr', dur: '5.5 Years', seats: 200 }
  ],
  topRecruiter: 'Govt Hospitals',
  avgPkg: '₹9 LPA',
  highPkg: '₹20 LPA',
  placed: '100%',
  campus: 'Hospital | Labs | Hostel',
  estYear: 1959,
  accreditation: 'MCI',
  hostel: true,
  scholarship: true
},

{
  id: 30,
  name: 'Gangadhar Meher University',
  short: 'GMU',
  loc: 'Sambalpur',
  type: 'Government',
  stream: 'Arts',
  rating: 4.2,
  reviews: 2100,
  fees: '₹28K/yr',
  placement: '₹4.5 LPA',
  rank: 30,
  color: '#6C3483',
  badge: '🎓 State Univ',
  tags: ['Arts', 'Science'],
  score: 70,
  website: 'https://gmuniversity.ac.in',
  image: 'https://th.bing.com/th/id/OIP.VMKjsnmPM6cHXLJaOqs4tQHaE8?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
  logo: '',
  desc: 'GMU is a well-known state university offering UG and PG programs in arts and science.',
  courses: [
    { name: 'B.Sc', fee: '₹28K/yr', dur: '3 Years', seats: 400 }
  ],
  topRecruiter: 'Govt, Teaching',
  avgPkg: '₹4.5 LPA',
  highPkg: '₹10 LPA',
  placed: '60%',
  campus: 'Library | Labs | Sports',
  estYear: 1944,
  accreditation: 'NAAC A',
  hostel: true,
  scholarship: true
},

{
  id: 31,
  name: 'Berhampur University',
  short: 'BU',
  loc: 'Berhampur',
  type: 'Government',
  stream: 'Arts',
  rating: 4.0,
  reviews: 1800,
  fees: '₹30K/yr',
  placement: '₹4 LPA',
  rank: 31,
  color: '#1F618D',
  badge: '🏛️ Univ',
  tags: ['Arts', 'Law', 'Science'],
  score: 68,
  website: 'https://buodisha.edu.in',
  image: 'https://th.bing.com/th/id/OIP.D7CVYW_4y_ntTKEJjJRM-wHaE8?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
  logo: '',
  desc: 'Berhampur University offers diverse programs with a strong academic base in southern Odisha.',
  courses: [
    { name: 'BA', fee: '₹30K/yr', dur: '3 Years', seats: 500 }
  ],
  topRecruiter: 'Govt, NGOs',
  avgPkg: '₹4 LPA',
  highPkg: '₹9 LPA',
  placed: '58%',
  campus: 'Green Campus | Library',
  estYear: 1967,
  accreditation: 'NAAC B+',
  hostel: true,
  scholarship: true
},

{
  id: 32,
  name: 'GIET University',
  short: 'GIET',
  loc: 'Gunupur',
  type: 'Private',
  stream: 'Engineering',
  rating: 4.1,
  reviews: 1600,
  fees: '₹1.6L/yr',
  placement: '₹5.5 LPA',
  rank: 32,
  color: '#117A65',
  badge: '⚙️ Engineering',
  tags: ['B.Tech', 'MBA'],
  score: 72,
  website: 'https://giet.edu',
  image: 'https://th.bing.com/th/id/OIP.b80O6vyjq8oeYeDslQC4xAHaFj?o=7rm=3&rs=1&pid=ImgDetMain&o=7&rm=3',
  logo: '',
  desc: 'GIET University is known for engineering and management programs with decent placement support.',
  courses: [
    { name: 'B.Tech', fee: '₹1.6L/yr', dur: '4 Years', seats: 400 }
  ],
  topRecruiter: 'Infosys, Wipro',
  avgPkg: '₹5.5 LPA',
  highPkg: '₹14 LPA',
  placed: '75%',
  campus: 'Labs | Hostel | Sports',
  estYear: 1997,
  accreditation: 'NAAC B+',
  hostel: true,
  scholarship: true
},
{
  id: 33,
  name: 'BPUT Odisha',
  short: 'BPUT',
  loc: 'Rourkela',
  type: 'Government',
  stream: 'Engineering',
  rating: 4.0,
  reviews: 1200,
  fees: '₹90K/yr',
  placement: '₹5 LPA',
  rank: 33,
  color: '#1A5276',
  badge: '🏛️ State Tech Univ',
  tags: ['B.Tech', 'M.Tech'],
  score: 70,
  website: 'https://bput.ac.in',
  image: 'https://bputmic.in/assets/1-CN3rGelV.webp',
  logo: '',
  desc: 'BPUT is the technical university affiliating most engineering colleges in Odisha.',
  courses: [
    { name: 'B.Tech', fee: '₹90K/yr', dur: '4 Years', seats: 500 }
  ],
  topRecruiter: 'TCS, Infosys',
  avgPkg: '₹5 LPA',
  highPkg: '₹12 LPA',
  placed: '70%',
  campus: 'Academic Blocks | Library',
  estYear: 2002,
  accreditation: 'NAAC',
  hostel: true,
  scholarship: true
},

{
  id: 34,
  name: 'Nalanda Institute of Technology',
  short: 'NITEC',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Engineering',
  rating: 3.9,
  reviews: 900,
  fees: '₹1.1L/yr',
  placement: '₹4.5 LPA',
  rank: 34,
  color: '#2E4053',
  badge: '🎓 Engineering',
  tags: ['B.Tech'],
  score: 64,
  website: 'https://nalandainstitute.ac.in',
  image: 'https://tse1.mm.bing.net/th/id/OIP.4GegUizGgdOOyiV_O3uvJAAAAA?rs=1&pid=ImgDetMain&o=7&rm=3',
  logo: '',
  desc: 'Nalanda Institute offers engineering programs with decent infrastructure.',
  courses: [
    { name: 'B.Tech', fee: '₹1.1L/yr', dur: '4 Years', seats: 300 }
  ],
  topRecruiter: 'Infosys, TCS',
  avgPkg: '₹4.5 LPA',
  highPkg: '₹10 LPA',
  placed: '65%',
  campus: 'Labs | Hostel',
  estYear: 2006,
  accreditation: 'AICTE',
  hostel: true,
  scholarship: false
},

{
  id: 35,
  name: 'Einstein Academy of Technology',
  short: 'EAT',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Engineering',
  rating: 3.7,
  reviews: 700,
  fees: '₹1L/yr',
  placement: '₹4 LPA',
  rank: 35,
  color: '#5D6D7E',
  badge: '⚙️ Engineering',
  tags: ['B.Tech'],
  score: 60,
  website: 'https://eat.edu.in',
  image: 'https://i.ytimg.com/vi/Bla0TyCoOnM/maxresdefault.jpg',
  logo: '',
  desc: 'Einstein Academy provides affordable engineering education.',
  courses: [
    { name: 'B.Tech', fee: '₹1L/yr', dur: '4 Years', seats: 240 }
  ],
  topRecruiter: 'TCS, Wipro',
  avgPkg: '₹4 LPA',
  highPkg: '₹8 LPA',
  placed: '60%',
  campus: 'Labs | Hostel',
  estYear: 2009,
  accreditation: 'AICTE',
  hostel: true,
  scholarship: false
},

{
  id: 36,
  name: 'Oxford College of Engineering',
  short: 'OCE',
  loc: 'Bhubaneswar',
  type: 'Private',
  stream: 'Engineering',
  rating: 3.8,
  reviews: 800,
  fees: '₹1.2L/yr',
  placement: '₹4.2 LPA',
  rank: 36,
  color: '#7D6608',
  badge: '🎓 Engineering',
  tags: ['B.Tech'],
  score: 62,
  website: 'https://oxford.edu.in',
  image: 'https://tse2.mm.bing.net/th/id/OIP.LORz04smYn7DF6hn0IEqbAHaE8?rs=1&pid=ImgDetMain&o=7&rm=3',
  logo: '',
  desc: 'Oxford College offers engineering programs with decent facilities.',
  courses: [
    { name: 'B.Tech', fee: '₹1.2L/yr', dur: '4 Years', seats: 300 }
  ],
  topRecruiter: 'Infosys, Wipro',
  avgPkg: '₹4.2 LPA',
  highPkg: '₹9 LPA',
  placed: '62%',
  campus: 'Labs | Library',
  estYear: 2008,
  accreditation: 'AICTE',
  hostel: true,
  scholarship: false
},
{
  id: 37,
  name: 'College of Engineering and Technology',
  short: 'CET',
  loc: 'Bhubaneswar',
  type: 'Government',
  stream: 'Engineering',
  rating: 4.4,
  reviews: 2600,
  fees: '₹70K/yr',
  placement: '₹7 LPA',
  rank: 37,
  color: '#1F618D',
  badge: '🏛️ Top Govt Engg',
  tags: ['B.Tech', 'M.Tech'],
  score: 82,
  website: 'https://cet.edu.in',
  image: 'https://www.gkseries.com/blog/wp-content/uploads/2020/03/College-of-Engineering-and-Technology-Bhubaneswar.jpg',
  logo: '',
  desc: 'CET Bhubaneswar is one of the top government engineering colleges in Odisha with strong academic reputation.',
  courses: [
    { name: 'B.Tech CSE', fee: '₹70K/yr', dur: '4 Years', seats: 120 },
    { name: 'B.Tech Civil', fee: '₹70K/yr', dur: '4 Years', seats: 120 }
  ],
  topRecruiter: 'TCS, Infosys, Capgemini',
  avgPkg: '₹7 LPA',
  highPkg: '₹20 LPA',
  placed: '85%',
  campus: 'Green Campus | Labs | Hostels',
  estYear: 1981,
  accreditation: 'NAAC A',
  hostel: true,
  scholarship: true
},

{
  id: 38,
  name: 'Government College of Engineering Keonjhar',
  short: 'GCEKJ',
  loc: 'Keonjhar',
  type: 'Government',
  stream: 'Engineering',
  rating: 4.0,
  reviews: 800,
  fees: '₹80K/yr',
  placement: '₹5 LPA',
  rank: 38,
  color: '#196F3D',
  badge: '🏛️ Govt Engg',
  tags: ['B.Tech'],
  score: 70,
  website: 'https://gcekjr.ac.in',
  image: 'https://th.bing.com/th/id/R.8d1b5320b095bd003aa723811ddef7a2?rik=G6oI4KiaTaZnOQ&riu=http%3a%2f%2fwww.gcekjr.ac.in%2fimages%2fgallery%2fbig%2f20171201130117COLLEGE+FRON+VIEW.jpg&ehk=plzvqGZRnz5lI4CD1zOO%2bN23f4a%2bzx9uM2xIczLLzcA%3d&risl=&pid=ImgRaw&r=0',
  logo: '',
  desc: 'A government engineering college providing quality education in northern Odisha.',
  courses: [
    { name: 'B.Tech Mechanical', fee: '₹80K/yr', dur: '4 Years', seats: 120 }
  ],
  topRecruiter: 'TCS, Tata Steel',
  avgPkg: '₹5 LPA',
  highPkg: '₹12 LPA',
  placed: '70%',
  campus: 'Labs | Hostel',
  estYear: 2012,
  accreditation: 'AICTE',
  hostel: true,
  scholarship: true
},

{
  id: 39,
  name: 'Government College of Engineering Koraput',
  short: 'GCEK',
  loc: 'Koraput',
  type: 'Government',
  stream: 'Engineering',
  rating: 3.9,
  reviews: 700,
  fees: '₹80K/yr',
  placement: '₹4.5 LPA',
  rank: 39,
  color: '#7D3C98',
  badge: '🏛️ Govt Engg',
  tags: ['B.Tech'],
  score: 68,
  website: 'https://gcekp.ac.in',
  image: 'https://gcekp.ac.in/images/campus.jpg',
  logo: '',
  desc: 'GCE Koraput is a developing government engineering institute in southern Odisha.',
  courses: [
    { name: 'B.Tech Civil', fee: '₹80K/yr', dur: '4 Years', seats: 120 }
  ],
  topRecruiter: 'Infosys, TCS',
  avgPkg: '₹4.5 LPA',
  highPkg: '₹10 LPA',
  placed: '65%',
  campus: 'Campus | Labs',
  estYear: 2010,
  accreditation: 'AICTE',
  hostel: true,
  scholarship: true
},

{
  id: 40,
  name: 'Regional Institute of Education',
  short: 'RIE',
  loc: 'Bhubaneswar',
  type: 'Government',
  stream: 'Education',
  rating: 4.3,
  reviews: 600,
  fees: '₹20K/yr',
  placement: '₹4 LPA',
  rank: 40,
  color: '#117A65',
  badge: '📚 Teaching',
  tags: ['B.Ed', 'M.Ed'],
  score: 75,
  website: 'https://riebbs.ac.in',
  image: 'https://riebbs.ac.in/images/campus.jpg',
  logo: '',
  desc: 'RIE Bhubaneswar is an NCERT institute for teacher education.',
  courses: [
    { name: 'B.Ed', fee: '₹20K/yr', dur: '2 Years', seats: 100 }
  ],
  topRecruiter: 'Schools, Govt Jobs',
  avgPkg: '₹4 LPA',
  highPkg: '₹8 LPA',
  placed: '80%',
  campus: 'Academic Blocks | Hostel',
  estYear: 1963,
  accreditation: 'NAAC A',
  hostel: true,
  scholarship: true
},

{
  id: 41,
  name: 'Central University of Odisha',
  short: 'CUO',
  loc: 'Koraput',
  type: 'Government',
  stream: 'Arts',
  rating: 4.2,
  reviews: 900,
  fees: '₹35K/yr',
  placement: '₹5 LPA',
  rank: 41,
  color: '#6C3483',
  badge: '🏛️ Central Univ',
  tags: ['Arts', 'Science'],
  score: 78,
  website: 'https://cuo.ac.in',
  image: 'https://assets.odishabytes.com/wp-content/uploads/2017/05/CUO.jpg',
  logo: '',
  desc: 'Central University of Odisha offers diverse programs with a national-level curriculum.',
  courses: [
    { name: 'BA', fee: '₹35K/yr', dur: '3 Years', seats: 300 },
    { name: 'M.Sc', fee: '₹40K/yr', dur: '2 Years', seats: 150 }
  ],
  topRecruiter: 'Govt, NGOs',
  avgPkg: '₹5 LPA',
  highPkg: '₹12 LPA',
  placed: '65%',
  campus: 'Green Campus | Labs',
  estYear: 2009,
  accreditation: 'NAAC B+',
  hostel: true,
  scholarship: true
}
];

// ═══════════════════════════════════════════
// ENTRANCE EXAMS
// ═══════════════════════════════════════════
const EXAMS = [
  {
    name: 'OJEE 2025',
    full: 'Odisha Joint Entrance Examination',
    icon: '📐',
    cat: 'Engineering',
    level: 'State',
    date: 'May 2025',
    regDeadline: 'Mar 31, 2025',
    mode: 'Online',
    status: 'open',
    eligible: '10+2 Pass',
    website: 'https://ojee.nic.in',
    desc: 'State-level entrance exam for lateral entry to B.Tech, B.Pharm and MCA programs in Odisha colleges.'
  },
  {
    name: 'NEET UG 2025',
    full: 'National Eligibility cum Entrance Test',
    icon: '🏥',
    cat: 'Medical',
    level: 'National',
    date: 'May 4, 2025',
    regDeadline: 'Closed',
    mode: 'Offline',
    status: 'soon',
    eligible: '10+2 (PCB)',
    website: 'https://neet.nta.nic.in',
    desc: 'National-level entrance exam for MBBS, BDS and other medical courses across India including all Odisha medical colleges.'
  },
  {
    name: 'JEE Main 2025',
    full: 'Joint Entrance Examination Main',
    icon: '⚙️',
    cat: 'Engineering',
    level: 'National',
    date: 'Jan 22–31',
    regDeadline: 'Closed',
    mode: 'Online',
    status: 'closed',
    eligible: '10+2 (PCM)',
    website: 'https://jeemain.nta.nic.in',
    desc: 'National-level entrance exam for admission to B.Tech programs at NITs, IIITs, GFTIs and other top engineering colleges.'
  },
  {
    name: 'CAT 2025',
    full: 'Common Admission Test',
    icon: '💼',
    cat: 'MBA',
    level: 'National',
    date: 'Nov 2025',
    regDeadline: 'Sep 2025',
    mode: 'Online',
    status: 'soon',
    eligible: 'Graduation',
    website: 'https://iimcat.ac.in',
    desc: 'Common Admission Test conducted by IIMs for admission to MBA and PGDM programs at IIMs and other top B-schools.'
  },
  {
    name: 'CUET UG 2025',
    full: 'Common University Entrance Test',
    icon: '🎓',
    cat: 'Engineering',
    level: 'National',
    date: 'May–Jun 2025',
    regDeadline: 'Apr 2025',
    mode: 'Online',
    status: 'open',
    eligible: '10+2 Pass',
    website: 'https://cuet.samarth.ac.in',
    desc: 'NTA-conducted exam for admission to UG programs at central universities and participating institutions across India.'
  },
  {
    name: 'OPSC OAS 2025',
    full: 'Odisha Public Service Commission',
    icon: '⚕️',
    cat: 'State',
    level: 'State',
    date: 'Jun 2025',
    regDeadline: 'Apr 15, 2025',
    mode: 'Offline',
    status: 'open',
    eligible: 'Graduation',
    website: 'https://opsc.gov.in',
    desc: 'State civil service exam for Odisha Administrative Service positions. Open to graduates from all streams.'
  },
  {
    name: 'OJEE MBA 2025',
    full: 'Odisha JEE MBA Entrance',
    icon: '📊',
    cat: 'MBA',
    level: 'State',
    date: 'May 2025',
    regDeadline: 'Mar 25, 2025',
    mode: 'Online',
    status: 'open',
    eligible: 'Graduation',
    website: 'https://ojee.nic.in',
    desc: 'State-level MBA entrance for direct admission to 2-year MBA programs in Odisha universities and colleges.'
  },
  {
    name: 'NATA 2025',
    full: 'National Aptitude Test in Architecture',
    icon: '🏗️',
    cat: 'Engineering',
    level: 'National',
    date: 'Apr 2025',
    regDeadline: 'Mar 20, 2025',
    mode: 'Online',
    status: 'soon',
    eligible: '10+2 (PCM/PCB)',
    website: 'https://nata.in',
    desc: 'Aptitude test for admission to 5-year B.Arch programs at architecture schools across India.'
  }
];

// ═══════════════════════════════════════════
// NEWS
// ═══════════════════════════════════════════
const NEWS_DATA = [
  {
    cat: 'Admission',
    title: 'OJEE 2025 Application Form Released – Check Eligibility & Last Date',
    excerpt: 'The Odisha Joint Entrance Examination Board has released the OJEE 2025 application form. Students can apply online before March 31, 2025. Check all important details here.',
    date: 'March 15, 2025',
    emoji: '📰',
    bg: 'linear-gradient(135deg,#1A1A2E,#16213E)',
    trending: true
  },
  {
    cat: 'Rankings',
    title: 'NIRF Rankings 2025: NIT Rourkela Climbs to Top 20 Engineering Colleges in India',
    excerpt: 'NIT Rourkela has significantly improved its NIRF ranking, securing a spot in the top 20 engineering institutions. The institute received 94.5 out of 100 on research parameters.',
    date: 'March 12, 2025',
    emoji: '🏆',
    bg: 'linear-gradient(135deg,#0F3460,#16213E)',
    trending: true
  },
  {
    cat: 'Results',
    title: 'CHSE Odisha Class 12 Result 2025 Expected in May – Direct Link Here',
    excerpt: 'The Council of Higher Secondary Education (CHSE), Odisha is likely to declare the Class 12 results in the third week of May 2025. Students can check results at chseodisha.nic.in.',
    date: 'March 10, 2025',
    emoji: '🎓',
    bg: 'linear-gradient(135deg,#145A32,#1E8449)',
    trending: false
  },
  {
    cat: 'Scholarship',
    title: 'Odisha Medhabruti Scholarship 2025: Applications Open for Class 11 to PG Students',
    excerpt: 'The Odisha government has opened applications for the Medhabruti Scholarship 2025 for meritorious students across various streams. Apply before April 30.',
    date: 'March 8, 2025',
    emoji: '💰',
    bg: 'linear-gradient(135deg,#7D6608,#9A7D0A)',
    trending: true
  },
  {
    cat: 'Infrastructure',
    title: 'New IIM Campus to be Set Up in Sambalpur – Odisha Government Confirms Land Allocation',
    excerpt: 'The Odisha government has allocated 200 acres of land for a new IIM campus in Sambalpur, expected to start functioning from 2027.',
    date: 'March 5, 2025',
    emoji: '🏗️',
    bg: 'linear-gradient(135deg,#1A5276,#1F618D)',
    trending: false
  },
  {
    cat: 'Placement',
    title: 'KIIT University Records ₹45 LPA Highest Package in 2024–25 Placement Season',
    excerpt: 'KIIT University recorded its best-ever placement season with over 3000 students placed and a highest package of ₹45 LPA from a top tech firm.',
    date: 'March 3, 2025',
    emoji: '📊',
    bg: 'linear-gradient(135deg,#1A5C37,#1E8449)',
    trending: false
  }
];

// ═══════════════════════════════════════════
// SCHOLARSHIPS
// ═══════════════════════════════════════════
const SCHOLARSHIPS = [
  {
    name: 'Medhabruti Scholarship',
    org: 'Odisha Government',
    icon: '🎓',
    amount: '₹1,200',
    per: 'per month',
    eligibility: 'Class 11–PG, Merit basis',
    deadline: 'April 30, 2025',
    category: 'Merit Based',
    coverage: 'Full Tuition',
    link: 'https://scholarship.odisha.gov.in'
  },
  {
    name: 'Post-Matric Scholarship SC/ST',
    org: 'Ministry of Social Justice',
    icon: '🏛️',
    amount: '₹1,500',
    per: 'per month',
    eligibility: 'SC/ST Students',
    deadline: 'October 2025',
    category: 'SC/ST/OBC',
    coverage: 'Tuition + Maintenance',
    link: 'https://scholarships.gov.in'
  },
  {
    name: 'National Scholarship Portal',
    org: 'Ministry of Education',
    icon: '🌐',
    amount: '₹10,000',
    per: 'per year',
    eligibility: 'Class 9–12, Below ₹3.5L income',
    deadline: 'November 2025',
    category: 'Need Based',
    coverage: 'Partial Tuition',
    link: 'https://scholarships.gov.in'
  },
  {
    name: 'KIIT Merit Scholarship',
    org: 'KIIT University',
    icon: '⭐',
    amount: '₹50,000',
    per: 'per year',
    eligibility: 'JEE Main Rank <5000',
    deadline: 'July 2025',
    category: 'Merit Based',
    coverage: 'Partial Tuition',
    link: 'https://www.kiit.ac.in/scholarship'
  },
  {
    name: 'INSPIRE Fellowship',
    org: 'DST, Govt. of India',
    icon: '🔬',
    amount: '₹80,000',
    per: 'per year',
    eligibility: 'B.Sc/M.Sc Science, Top 1%',
    deadline: 'December 2025',
    category: 'Merit Based',
    coverage: 'Full Stipend',
    link: 'https://online-inspire.gov.in'
  },
  {
    name: 'PRERANA Scholarship',
    org: 'Odisha Tribal Development',
    icon: '🌿',
    amount: '₹2,000',
    per: 'per month',
    eligibility: 'ST Students, Odisha Domicile',
    deadline: 'September 2025',
    category: 'SC/ST/OBC',
    coverage: 'Full Maintenance',
    link: 'https://scholarship.odisha.gov.in'
  }
];

// ═══════════════════════════════════════════
// TESTIMONIALS
// ═══════════════════════════════════════════
const TESTIMONIALS = [
  {
    name: 'Priya Patra',
    college: 'IIT Bhubaneswar',
    stream: 'B.Tech CSE',
    year: '2024 Passout',
    text: 'CollegeHub helped me compare IIT Bhubaneswar with other colleges. The placement data was spot on. Got placed at Google with ₹1.2 CPA package!',
    avatar: '👩‍💻',
    rating: 5
  },
  {
    name: 'Rahul Mishra',
    college: 'AIIMS Bhubaneswar',
    stream: 'MBBS',
    year: '2023 Batch',
    text: 'The AI counselor Vidya was incredibly helpful in guiding me through NEET preparation and college selection. Now I\'m a proud AIIMS student!',
    avatar: '👨‍⚕️',
    rating: 5
  },
  {
    name: 'Sneha Das',
    college: 'XIM University',
    stream: 'MBA',
    year: '2024 Batch',
    text: 'The scholarship finder tool saved me months of research. Found Medhabruti scholarship through this site. XIM is everything CollegeHub said it would be.',
    avatar: '👩‍💼',
    rating: 5
  },
  {
    name: 'Amit Kumar',
    college: 'NIT Rourkela',
    stream: 'B.Tech Mech',
    year: '2023 Passout',
    text: 'Used the college comparison tool to decide between NIT Rourkela and VSSUT. Made the right choice! Campus data was accurate and very helpful.',
    avatar: '👨‍🔧',
    rating: 4
  }
];

// Export for use across files
if (typeof module !== 'undefined') {
  module.exports = { COLLEGES, EXAMS, NEWS_DATA, SCHOLARSHIPS, TESTIMONIALS };
}
